import json
import logging
import re
from datetime import datetime
from zoneinfo import ZoneInfo

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langfuse import Langfuse, get_client, observe, propagate_attributes

from config.settings import settings
from core.prompt_loader import load_prompt_config

load_dotenv()

logger = logging.getLogger("compliance")

langfusePrompt = Langfuse(
    public_key=settings.LANGFUSE_PUBLIC_KEY,
    secret_key=settings.LANGFUSE_SECRET_KEY,
    host=settings.LANGFUSE_BASE_URL,
)
langfuse = get_client()

BLOCK_FALLBACK_MESSAGE = "This output has been blocked due to compliance violations. Please ask another question."
ERROR_FALLBACK_MESSAGE = "An error has occurred. Please try again later."
MEDICAL_DISCLAIMER = (
    "⚕️ Disclaimer: This response is generated by an AI system and is intended "
    "for informational purposes only. It does not constitute medical advice, "
    "diagnosis, or treatment. Always consult a qualified healthcare professional "
    "before making any medical decisions."
)

ALLOWABLE_HEALTH_INTERPRETATION_PATTERNS = [
    r"\bbmi\b",
    r"blood pressure",
    r"cholesterol",
    r"fasting glucose",
    r"hba1c",
    r"prediabet",
    r"risk for conditions like",
    r"discuss these results with a healthcare provider",
]

DISALLOWED_CONTENT_PATTERNS = [
    r"ignore previous instructions",
    r"system prompt",
    r"synthesi[sz]e dangerous substances",
    r"build (?:a )?bomb",
    r"harm yourself",
    r"kill yourself",
    r"take\s+\d+\s*mg",
]

CRITICAL_BLOCK_REASON_PATTERNS = [
    r"pii",
    r"personally identifiable",
    r"name",
    r"nric",
    r"fin",
    r"phone",
    r"email",
    r"address",
    r"dosage",
    r"treatment plan",
    r"specific doctor",
    r"specific clinic",
    r"harmful",
    r"violent",
    r"sexual",
    r"discriminatory",
    r"prompt injection",
    r"system prompt",
]

SOFT_FALSE_POSITIVE_REASON_PATTERNS = [
    r"potentially sensitive medical interpretation",
    r"sensitive medical interpretation",
    r"medical interpretation",
    r"potentially sensitive",
]


def now():
    return datetime.now(ZoneInfo("Asia/Singapore")).isoformat()


def _append_disclaimer(text: str) -> str:
    if not text:
        return MEDICAL_DISCLAIMER
    if MEDICAL_DISCLAIMER in text:
        return text
    return f"{text}\n\n{MEDICAL_DISCLAIMER}"


def _looks_like_allowable_health_interpretation(text: str, reasons: list[str]) -> bool:
    normalized_text = (text or "").lower()
    normalized_reasons = " ".join(reasons or []).lower()

    has_allowed_pattern = any(
        re.search(pattern, normalized_text)
        for pattern in ALLOWABLE_HEALTH_INTERPRETATION_PATTERNS
    )
    has_disallowed_pattern = any(
        re.search(pattern, normalized_text) for pattern in DISALLOWED_CONTENT_PATTERNS
    )
    false_positive_reason = any(
        phrase in normalized_reasons
        for phrase in [
            "specific health measurements",
            "potential health risks",
            "lab values",
            "test results",
            "medical",
            "diagnosis",
            "treatment",
        ]
    )

    return has_allowed_pattern and not has_disallowed_pattern and false_positive_reason


def _contains_clear_block_signal(text: str, reasons: list[str]) -> bool:
    normalized_text = (text or "").lower()
    normalized_reasons = " ".join(reasons or []).lower()

    if any(
        re.search(pattern, normalized_text) for pattern in DISALLOWED_CONTENT_PATTERNS
    ):
        return True

    return any(
        re.search(pattern, normalized_reasons)
        for pattern in CRITICAL_BLOCK_REASON_PATTERNS
    )


def _looks_like_soft_false_positive(reasons: list[str]) -> bool:
    normalized_reasons = " ".join(reasons or []).lower()
    return any(
        re.search(pattern, normalized_reasons)
        for pattern in SOFT_FALSE_POSITIVE_REASON_PATTERNS
    )


@observe(as_type="generation")
def compliance_node(state):
    """
    Generate insight summary from report text using LLM.
    """

    try:
        # Check if final_response already exists in state, if so return early to avoid redundant processing
        if state.final_response:
            logger.info(
                "Skip compliance check as final_response already exists in state."
            )
            return {"next_node": "END", "last_updated": now()}

        # Load prompt config from JSON
        version = settings.PROMPT_VERSIONS.get(
            "compliance", settings.DEFAULT_PROMPT_VERSION
        )
        analysis_config = load_prompt_config(
            module="compliance", key="compliance", version=version
        )

        # langfuse prompt managment (START)
        try:
            prompt = langfusePrompt.get_prompt("compliance/systemPrompt")
            system_prompt = prompt.compile()
            config = prompt.config
            model = config.get("model", "gpt-4o-mini")
            temperature = config.get("temperature", 0.2)
            logger.info(
                f"Langfuse prompt fetched successfully: version {prompt.version}"
            )
        except Exception:
            # fallback to local prompt config if langfuse prompt retrieval fails
            logger.info(
                "Failed to load system prompt from Langfuse, falling back to local prompt config."
            )
            system_prompt = analysis_config["system"]
            model = analysis_config["model"]
            temperature = analysis_config["temperature"]
            prompt = None
        # langfuse prompt managment (END)

        # Call LLM for classification with config from prompts.json
        llm = ChatOpenAI(model=model, temperature=temperature)
        response = llm.invoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(content=state.pre_compliance_response),
            ]
        )

        # Update langfuse monitoring w/o prompt management
        langfuse.update_current_generation(
            usage_details=response.response_metadata.get("token_usage"),
            model=response.response_metadata.get("model_name"),
            prompt=prompt,
        )

        # Add langfuse session tracking
        with propagate_attributes(
            session_id=state.session_id,
            user_id=state.session_id,
            trace_name="compliance",
        ):
            pass

        result = response.content.strip()

        # Parse JSON response from LLM
        # Strip markdown code fences if present
        clean_result = result.replace("```json", "").replace("```", "").strip()
        compliance_response = json.loads(clean_result)

        verdict = compliance_response.get("verdict", "block")
        reasons = compliance_response.get("reasons", [])
        final_response = compliance_response.get(
            "final_response", BLOCK_FALLBACK_MESSAGE
        )

        if verdict == "block" and _looks_like_allowable_health_interpretation(
            state.pre_compliance_response, reasons
        ):
            verdict = "pass"
            final_response = _append_disclaimer(state.pre_compliance_response)
            compliance_response["verdict"] = verdict
            compliance_response["reasons"] = [
                "Informational health-result interpretation allowed with disclaimer."
            ]
            compliance_response["disclaimer_injected"] = True
            compliance_response["sanitized_output"] = None
            compliance_response["final_response"] = final_response

        # If the model blocks a clearly informational health explanation without
        # any strong unsafe signal, treat it as a false positive and pass with disclaimer.
        if (
            verdict == "block"
            and _looks_like_allowable_health_interpretation(
                state.pre_compliance_response, reasons
            )
            and _looks_like_soft_false_positive(reasons)
            and not _contains_clear_block_signal(state.pre_compliance_response, reasons)
        ):
            verdict = "pass"
            final_response = _append_disclaimer(state.pre_compliance_response)
            compliance_response["verdict"] = verdict
            compliance_response["reasons"] = [
                "No clear compliance violation detected in informational content."
            ]
            compliance_response["disclaimer_injected"] = True
            compliance_response["sanitized_output"] = None
            compliance_response["final_response"] = final_response

        # Safety net: if verdict is block but LLM forgot to set a safe final_response
        if verdict == "block":
            final_response = BLOCK_FALLBACK_MESSAGE
        elif compliance_response.get("disclaimer_injected"):
            final_response = _append_disclaimer(final_response)
            compliance_response["final_response"] = final_response

        logger.info(f"Compliance verdict: {verdict}")
        logger.info(f"Reasons: {compliance_response.get('reasons', [])}")

        return {
            "compliance_response": compliance_response,  # full JSON object
            "final_response": final_response,  # extracted for easy access
            "next_node": "END",
            "last_updated": now(),
        }

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse compliance LLM response as JSON: {str(e)}")
        return {
            "compliance_response": {
                "verdict": "block",
                "reasons": ["Compliance agent returned malformed response."],
                "sanitized_output": None,
                "final_response": BLOCK_FALLBACK_MESSAGE,
            },
            "final_response": BLOCK_FALLBACK_MESSAGE,
            "next_node": "END",
            "last_updated": now(),
        }

    except Exception as e:
        msg = str(e)
        short_msg = msg[:100] if len(msg) > 100 else msg
        logger.error(f"Error Encountered: {short_msg}")
        return {
            "compliance_response": {
                "verdict": "block",
                "reasons": [
                    f"Compliance check failed due to an internal error: {short_msg}"
                ],
                "sanitized_output": None,
                "final_response": ERROR_FALLBACK_MESSAGE,
            },
            "final_response": ERROR_FALLBACK_MESSAGE,
            "next_node": "END",
            "last_updated": now(),
        }
